create table genre
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    title       varchar(255)
);

insert into genre (description, title)
values ('', 'rock'),
       ('', 'metal'),
       ('', 'classic'),
       ('', 'jazz'),
       ('', 'blues'),
       ('', 'pop'),
       ('', 'funk'),
       ('', 'rap'),
       ('', 'hip-hop'),
       ('', 'disco'),
       ('', 'folk');